### ISSUE TITLE
Custom Template for Date

### ISSUE THREAD

**Issue by dummifiedme** [SilentVoid13/Templater#37] opened 2021-01-06 13:45 UTC
I was trying to create a tempplate to print a note n days from now using the example you had shared in the readme.
I tried to modify it by a bit. The command I used was

`powershell (Get-Date -UFormat '[[%Y-%m-%d | %A, %d %b]]' (Get-Date).addDays(1))`

It works fine in the Powershell, but throws an error in Obsidian.
![image](https://user-images.githubusercontent.com/68785729/103775184-b5f25f80-5053-11eb-81f3-e85ff028c699.png)

Upon more digging, I found that the `|` in the format is the cause of error. What should I do to get it right? I tried `\|`, but didn't work.

**Comment by benwalio** [comment] 2021-01-08 00:50
what error is obsidian throwing? i just tried it on mine (not using powershell, macos terminal) but it didn't have any issues creating a note with the same general link format that you posted above 

<img width="329" alt="Screen Shot 2021-01-07 at 19 49 19" src="https://user-images.githubusercontent.com/13092287/103961006-8a3dab00-5121-11eb-8b83-ac8cb7ec2aa5.png">

**Comment by dummifiedme** [comment] 2021-01-08 18:26
The Obsidian error is like a notification, I am not able to read it. In the editor though, it just doesn't convert to the expected date but stays just as the template {{}}.

Can you share the Templater command that you used?

**Comment by benwalio** [comment] 2021-01-08 20:41
mines going to be different because I'm using the OSX `date` command but here it is: `date -j +"[[%Y-%m-%d_%a|%Y-%m-%d]]"`

**Comment by TSSlade** [comment] 2021-01-14 21:58
I can affirm a similar experience to @dummifiedme's. My console (`Ctrl+Shift+I`) provides the following:

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
(unknown) Error with the template n° 2:
 Error: Command failed: powershell echo "[[$((Get-Date).AddDays(-7) | Get-Date -UFormat "%Y-%m-%d")]]"

    at ChildProcess.exithandler (child_process.js:312)
    at ChildProcess.emit (events.js:310)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286)
```

If I remove the `powershell ` prefix from the custom template command and just lead with `echo`, I get the following result (in context):
```
Previous meeting in series: [[{{"Get-Date -UFormat "%Y-%m-%d")"}}_05h00]]
```

That is _not_ an error, but it's also not the desired outcome. Any chance the plugin is having a hard time launching/communicating with the Powershell executable?

**Comment by TSSlade** [comment] 2021-01-14 22:16
Further follow-up: using the custom templates in the README:

![image](https://user-images.githubusercontent.com/3211478/104655697-ebf69b80-5672-11eb-926a-cfa21c75952f.png)
a.k.a.
  ```
  powershell (Get-Date -UFormat '%Y-%m-%d' (Get-Date).addDays(-1))
  ```
...added like so:
![image](https://user-images.githubusercontent.com/3211478/104655648-daad8f00-5672-11eb-8308-52401b93e161.png)
...these are the results:
![image](https://user-images.githubusercontent.com/3211478/104655619-ccf80980-5672-11eb-8edc-704d18e0dfce.png)

**Comment by dummifiedme** [comment] 2021-01-15 03:08
As far as I remember, I was able to get correct output when using a simple format, the problem arose when I decided to use square brackets and vertical bar in there.

But there must be something missing in the templater for sure.

**Comment by TSSlade** [comment] 2021-01-15 12:36
Confirmed that even with neither square brackets nor a pipe present, I experience the same failure mode:

![image](https://user-images.githubusercontent.com/3211478/104728090-403d6200-56eb-11eb-91ba-838de88ea371.png)

**Comment by SilentVoid13** [comment] 2021-01-15 19:40
@dummifiedme @TSSlade: There are some known issues with powershell and Templater that I haven't been able to resolve for now.
However if you want to get today's date minus a day offset, you can with the new internal template `{{tp_date}}`. With this, you're now able to specify a date offset as argument like so: `{{tp_date:offset="-3"}}`. You can also specify the date format with the `f` argument, i.e.  `{{tp_date:offset="-3", f="yyyy-MM-dd"}}`.
Update Templater to 0.5.7 to use it !
I'm closing this because this issue is similar to #9 or #15 for powershell problems, but don't hesitate to re-open this if you have any problem using `{{tp_date}}`

**Closed by SilentVoid13** 2021-01-15 19:40 UTC
Labels: question
