### ISSUE TITLE
tp.file.cursor: "Can't read property length of undefined"

### ISSUE THREAD

**Issue by j3tman** [SilentVoid13/Templater#469] opened 2021-12-12 06:31 UTC
**Plugin informations (please complete the following information):**

-   OS: Mac OS 10.15.7
-   Templater version: 1.9.9
-   Obsidian version: 0.13.8
-   Templater settings: Template folder location: "References/Templates/", Automatic jump to cursor: True

**Describe the bug**
I ran into the error described in the title when setting the cursor position in a simple template (e.g., a blank file with simply the `tp.file.cursor` command).  Upon closer inspection, I found the issue was occurring at the end of the `set_cursor_location` function.  It looks like the transaction handler is expecting the transaction object to contain a `changes` array and immediately attempts to loops over.  Manually adding `changes: []` to `transaction` fixed the issue locally for me.

**Expected behavior**
I expected the cursor to appear right where `tp.file.cursor(0)` is called in my template.

**Additional context**
I'm not sure if this is something weird with my Obsidian version, but thought I would share in case you can repro on your end. Feel free to close if this doesn't seem to cause any problems with your setup. Thanks for the excellent plugin!

**Comment by shabegom** [comment] 2022-01-13 13:24
This is an excellent bug report

**Comment by liamcain** [comment] 2022-03-18 22:24
It's been a while since you submitted this bug report so a lot could have changed but I'm not able to reproduce the issue in either the new editor or the legacy editor. I'm going to close the issue for now but feel free to reopen the issue if you're still experiencing the bug.

---

Tested on:
macOS 12.3
Obsidian v14.0
Templater v1.10.X

**Closed by liamcain** 2022-03-18 22:24 UTC
Labels: bug
