### ISSUE TITLE
frontmatter with square brackets and commas renders as no space between commas

### ISSUE THREAD

**Issue by filmgal** [SilentVoid13/Templater#321] opened 2021-08-10 23:50 UTC
Win10
Templater 1.8.1
Obsidian  v0.12.12

When frontmatter includes square brackets, e.g, `[itemA, item B]` or` ["itemA", "itemB"]`
using `tp.frontmatter.thatfield` displays without spaces after the comma:
expected result: 
`itemA, itemB`
actual result: 
`itemA,itmeB` (no space after the comma)

frontmatter:
`lbtags: ["tiff 2014", "2014", "usa", "tiff"]`
using `tp.frontmatter.lbtags` results in `tiff 2014,2014,usa,tiff` 

Note that I can't replace the comma with a 'comma space' either:

when the frontmatter is in this format: `lblists: test1,test2,test3`
I can write this: `<%* tR += tp.frontmatter.lblists.replace(/\,+/g, ", "); %>`
and the result is this: `test1, test2, test3` (it replaces comma with comma + space)

But when there are brackets in the frontmatter like this:
`lbtags: ["tiff 2014", "2014", "usa", "tiff"]
and I write this:  `<%* tR += tp.frontmatter.lbtags.replace(/\,+/g, ", "); %>`
the result is a templater error.

**Comment by welpdx** [comment] 2021-08-11 03:59
@filmgal 
Yea ngl, I really dislike regex. 
If you just want to output that specific frontmatter into text, why don't you try this:
```
<%* tR += tp.frontmatter.lbtags.join(", ") %>
```
<br>

For `lbtags: ["tiff 2014", "2014", "usa", "tiff"]` 
- `tp.frontmatter.lbtags` is an array. (Whereas for `lblists: test1,test2,test3`, `tp.frontmatter.lblists` is a list of strings) 
- output of above script is `tiff 2014, 2014, usa, tiff`. 

Hope that helps.

**Comment by filmgal** [comment] 2021-08-11 21:24
Thanks - the join works but for one thing: if my value is a single, I get an error.

So I tried this (replacing the key for each item in the frontmatter).
```
<%-* if (tp.frontmatter?.director) { %>
<%* if (tp.frontmatter.director.includes(",")) { %>
d: (<%-* tR += tp.frontmatter.director.join(", ") %>)
<%-* } else { %>
d: <%tp.frontmatter.director%><%* } %>
<%-* } %>
```

My thinking was, if I check to see if there is a comma in the values then I would use the join, otherwise I would just display the single value.  That didn't work. The cinematographer frontmatter threw an error, and when I deleted it, the arrays ignored the join.

Frontmatter:
```
director: Isabel Coixet
cinematographer: Jean Valjean, Norm Sout
writer: [Sarah Kernochan, Isabel Coixet]
producer: ["Sally Anne", "Jim Shetland", "Nick Graves"]
```
Just trying to get one formula for everything because I never know what the values are going to be.

**Comment by welpdx** [comment] 2021-08-12 04:46
Good idea. There should be a length() function you can use for a boolean check. I just came back from a trip, Would look into it tmr on my pc.

**Comment by welpdx** [comment] 2021-08-13 19:25
Try this script below:
```
<%* // Final Code v3
var frontmatter1 = tp.frontmatter.director //change this line for different frontmatter
if (frontmatter1.constructor == String){ //If it is a string
	frontmatter1 = frontmatter1.split(",").join(", ")
	tR += frontmatter1
} else if (frontmatter1.constructor == Array){ //If it is an array
	new Notice("Array",2000)
	console.log(frontmatter1.join(", "))
	frontmatter1 = frontmatter1.join(", ")
	tR += frontmatter1
} else { //cant think of it being anything else. Delete lines below if annoying
	new Notice("Sumfing Wong. Please check Console (Ctrl + Shift + I)", 2000)
	console.log("Frontmatter is neither a String or Array? What is in this frontmatter?")
	tR += frontmatter1
}
%>
```
- What happened was that the frontmatter type changes depending on what is in it. If it is `director: Isabel Coixet` or `lblists: test1,test2,test3`, it is a string. If it is `lbtags: ["tiff 2014", "2014", "usa", "tiff"]` it is an list. 

In the script above:
- If frontmatter is a string, it turns it into a list with `split()` and then formats it the way you like it using `join()`. 
- If frontmatter is an array, simply use `join()` to format the way you like it. 

Let me know if it works for you.

**Comment by filmgal** [comment] 2021-08-15 20:36
Thanks. I'll give it a go soon.  This is just a workaround though, right? I mean it is a bug to render lists (arrays or strings) with commas without spaces?

**Comment by welpdx** [comment] 2021-08-16 19:32
No, it is not a bug. Like I mentioned above, the type of a particular frontmatter changes based on it's content. If it is a string or strings that has special characters in it (like commas in `lblists: test1,test2,test3`), If the content is an array (i.e., `lbtags: ["tiff 2014", "2014", "usa", "tiff"]`), the frontmatter would have an Array type. 

I guess I should really use switch case for this:

```
<%* 
var frontmatter1 = tp.frontmatter.array1 //change this line for different frontmatter
switch(frontmatter1.constructor) {  
	case String:  
		console.log("String")  
		console.log(frontmatter1.split(",").join(", "))
		frontmatter1 = frontmatter1.split(",").join(", ")
		tR += frontmatter1
		break;  
	case Array:  
		console.log(frontmatter1.join(", "))
		frontmatter1 = frontmatter1.join(", ")
		tR += frontmatter1
		break;  
	default:  
		console.log("Other")    
		tR += frontmatter1
}
%>
```

**Comment by filmgal** [comment] 2021-08-16 21:16
I should probably use Dataview then and stop using Templater. It's just too complicated to display frontmatter as proper comma separated lists, and no matter how often you explain it, I don't think I'm ever going to understand why lists can't be rendered with comma-space the way they do in dataview.
```
---
genre: ["comedy", "crime", "foreign", "music", "musical"]
country: [USA, Canada]
---
```


templater: `<% tp.frontmatter.genre %>`:  **comedy,crime,foreign,music,musical**
dataview: `dv: this.file.genre`: **comedy, crime, foreign, music, musical**

templater: `<% tp.frontmatter.country %>`: **Israel,Palestine,Lebanon**
dataview:  `dv: this.file.country`: **Israel, Palestine, Lebanon**

**Comment by welpdx** [comment] 2021-08-16 23:08
The script provided renders the output with comma-space. **It sufficiently fulfills your output requirement**. So instead of `<% tp.frontmatter.genre %>` try:
```
<%* 
var frontmatter1 = tp.frontmatter.genre //change this line for different frontmatter
switch(frontmatter1.constructor) {  
	case String:  
		console.log("String")  
		console.log(frontmatter1.split(",").join(", "))
		frontmatter1 = frontmatter1.split(",").join(", ")
		tR += frontmatter1
		break;  
	case Array:  
		console.log(frontmatter1.join(", "))
		frontmatter1 = frontmatter1.join(", ")
		tR += frontmatter1
		break;  
	default:  
		console.log("Other")    
		tR += frontmatter1
}
%>
```

#### With this script, you get the output you wanted.
![gif](https://i.imgur.com/jcgLoe2.gif)

#### Perhaps we were talking past each other lol. I think maybe you was trying to figure out why Templater's output does not have comma-space. While I was trying to explain why how my script works, that depending on the content of the frontmatter, the type changes. 
![pic](https://i.imgur.com/89tvD25.jpeg)

#### I think if dataview works best for you, go with dataview. But in your original question, it seemed like you were struggling with creating a script in Templater that outputs the frontmatter content with comma-space. That is what I have done here.

**Comment by filmgal** [comment] 2021-08-16 23:20
I am so thankful that you created that script for me, and I will definitely use it.  I guess I was so deflated by not being able to simply use `<% tp.frontmatter.genre %>`, which I know how to do, and to have to ask for a super complicated script to do something so simple (that I still insist should be done automatically without the script).

And you are correct, there is an element of talking past each other, and it is totally my fault. I started this thread with my attempts to circumvent the default behaviour and found that my attempt only worked for strings, not arrays, and you were so generous to give me a way to have my wish apply to both. But I have to say it again: hotdog this should not be so hard!

**Comment by welpdx** [comment] 2021-09-09 20:08
Hey no problem @filmgal,

I am very happy to help! Yea, there are tons of menes about how you could spend an hr coding but like a day debugging! Things just doesn't turn out to align with expectations sometimes. 
And communication in real life is already difficult enough, imagine it happen online with no context and non-verbal language! I'm surprised that people on the internet didn't accidentally start a war or something.

Anyways, please feel free to close this issue and make another if something else comes up. There are some cool scripst in the [Templater Discussions](https://github.com/SilentVoid13/Templater/discussions) too!

Welp~

<br>
> Hotdog? 

o.O

**Closed** 2021-09-10 05:07 UTC
Labels: bug
