### ISSUE TITLE
Codeblock requiring escape character to close

### ISSUE THREAD

**Issue by Jathosn** [SilentVoid13/Templater#1502] opened 2024-11-18 13:46 UTC
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 2.9.1
-   Obsidian version: 1.7.6
-   Templater settings: Syntax highlighting on desktop, automatic jump to cursor

**Describe the bug**
The addon breaks my code block and makes me unable to close it without adding an escape character.

With escape character:
```c
printf("%s </%s>\n", author->name, author->email);
```

Without escape character:
```c
printf("%s <%s>\n", author->name, author->email);
```

**Expected behavior**
I expect to be able to input any code inside my code blocks without it breaking

**Screenshots**
![Screenshot 2024-11-18 144426](https://github.com/user-attachments/assets/76acf747-d944-47b1-9056-86cc32453bac)

**Additional context**

**Comment by Zachatoo** [comment] 2024-11-18 14:22
This is a duplicate of #1204 , see that thread for the current status of this bug.

**Closed** 2024-11-18 14:23 UTC
Labels: bug
