### ISSUE TITLE
Template parsing error - with tp.web.daily_quote()

### ISSUE THREAD

**Issue by mjh8431** [SilentVoid13/Templater#742] opened 2022-08-31 17:22 UTC
**Plugin information (please complete the following information):**

-   OS: MacOS Monterey 12.3
-   Templater version: 1.12
-   Obsidian version: 15.9
-   Templater settings:  _Templates

**Describe the bug**
I have added this as a part of my daily note. 
<%tp.web.daily_quote()%>
It stopped working as of today. I now get a Rendering error alert that says to check the console.

**Expected behavior**
To provide a random note
![Snip20220831_3](https://user-images.githubusercontent.com/106125112/187740773-01f19a11-2de8-42a4-a594-fb2064268ac6.png)

**Screenshots**

**Additional context**

**Comment by shabegom** [comment] 2022-09-01 12:57
It appears the site that daily quotes are being fetched from is down

**Comment by shabegom** [comment] 2022-09-01 12:58
Duplicate of #739 closing

**Closed** 2022-09-01 12:58 UTC
Labels: bug
