### ISSUE TITLE
Templater file module does not support the concurrent creation of files

### ISSUE THREAD

**Issue by imagebuilder1837** [SilentVoid13/Templater#1405] opened 2024-06-24 16:13 UTC
**Plugin information (please complete the following information):**

-   OS: Windows 11
-   Templater version: 2.3.3
-   Obsidian version: 1.6.3
-   Templater settings: default

**Describe the bug**

A template is expected to generate different files for different folders when using it to generate files recursively in folders. But the resulting files are the same.

**Expected behavior**

Suppose there is a vault like this:

```
Vault/
├── dir1/
│   ├── dir11/
│   └── dir12/
├── dir2/
│   ├── dir21/
│   └── dir22/
└── template.md
```

`template.md`:

```javascript
Title: <% tp.file.title %>
<%*
var folders = app.vault.getAllLoadedFiles().filter(x => x instanceof tp.obsidian.TFolder);
for (i in folders) {
   var folder = folders[i];
   var file = app.vault.getFileByPath(`${folder.path}/${folder.name}.md`);
   if (folder.parent !== null && file === null) {  // avoid duplicate generation
      tp.file.create_new(tp.file.find_tfile('template'), folder.name, false, folder);
   }
}
-%>
```

Now use `template.md` to generate a `Untitled.md` file in the root directory:

```
Vault/
├── dir1/
│   ├── dir11/
│   │   └── dir11.md
│   ├── dir12/
│   │   └── dir12.md
│   └── dir1.md
├── dir2/
│   ├── dir21/
│   │   └── dir21.md
│   ├── dir22/
│   │   └── dir22.md
│   └── dir2.md
├── template.md
└── Untitled.md
```

Results:

`Untitled.md`:

```
Title: Untitled
```

`dir1.md` `dir2.md` `dir11.md` `dir12.md` `dir21.md` `dir22.md`:

```
Title: dir12
```

(Expected to be their own titles)

**Comment by imagebuilder1837** [comment] 2024-07-23 08:15
Thanks for your reply. Does this mean that Templater has no plans to support recursion?

**Comment by Zachatoo** [comment] 2024-07-23 14:08
Templater does support recursion. The Templater file module does not support the concurrent creation of files. If you create the files in sequence, the template works fine. There are no plans to adjust how this works, unless someone wants to volunteer to try to fix this.

```js
Title: <% tp.file.title %>
<%*
var folders = app.vault.getAllLoadedFiles().filter(x => x instanceof tp.obsidian.TFolder);
for (i in folders) {
   var folder = folders[i];
   var file = app.vault.getFileByPath(`${folder.path}/${folder.name}.md`);
   if (folder.parent !== null && file === null) {  // avoid duplicate generation
      // ADD AWAIT BELOW
      await tp.file.create_new(tp.file.find_tfile('template'), folder.name, false, folder);
   }
}
-%>
```

**Comment by Zachatoo** [comment] 2024-07-23 14:12
This is a duplicate of #1080 , marking as closed

**Closed by Zachatoo** 2024-07-23 14:12 UTC
Labels: bug
