### ISSUE TITLE
Frontmatter module, problem with new syntax

### ISSUE THREAD

**Issue by ArnoBuschmann** [SilentVoid13/Templater#98] opened 2021-04-12 00:40 UTC
**Plugin informations (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Templater version: [1.3.0]
 - Obsidian version: [0.11.13]
 - Templater settings: [folder location: "templates/", Timeout: "5"]

**Describe the bug**
Variables in frontmatter are not being rendered in the template and described as undefined in the output. The date module works as expected, just saying, Templater in general is working great, just except the  frontmatter module.

**Expected behavior**
Using the example from the documentation in the frontmatter/template:
```
---
alias: myfile
note type: seedling
---

File's metadata alias: <% tp.frontmatter.alias %>
Note's type: <% tp.frontmatter["note type"] %>
```
And getting this output:
```
---
alias: myfile
note type: seedling
---

File's metadata alias: undefined
Note's type: undefined
```

**Comment by SilentVoid13** [comment] 2021-04-12 12:25
Hey @ArnoBuschmann, I think you misunderstood how the `tp.frontmatter` module is working. 
`tp.frontmatter` will retrieve the frontmatter from the **destination** file, not the template file.
Retrieving frontmatter data from the template file doesn't make a lot of sense, since you already have access to that data anyway.

However if you insert a template containing:
```
File's metadata alias: <% tp.frontmatter.alias %>
Note's type: <% tp.frontmatter["note type"] %>
```

In a file containing:
```
---
alias: myfile
note type: seedling
---
```

Then it will work, as explained in the documentation.

This is not a bug, so I'll close this.

**Closed by SilentVoid13** 2021-04-12 12:25 UTC
Labels: bug

**Comment by ArnoBuschmann** [comment] 2021-04-12 14:25
Hi @SilentVoid13, oh yes, that works. Thanks a lot for clarification! :smiley:

**Comment by dagomar** [comment] 2023-08-28 09:52
Not sure if this is the right place, but I was looking for it and found a solution for my own use case. I needed to use frontmatter that I defined in my template file, because I needed to generate the template based on it, but also be able to use those frontmatter values in dataviews later on I found it is possible to access the frontmatter from the template file itself if you have dataview installed (probably there is a non-dataview way to do this):

```javascript
let template_path = tp.config.template_file.path;
// Note the [0] at the end, it's the first result from dataview, and it must be there because we're feeding it the template file path directly from the file itself
let dataview_page = app.plugins.plugins.dataview.api.pages(`"${tp.config.template_file.path}"`)[0];
let my_template_frontmatter_var = dataview_page.my_template_frontmatter
```
Or you can have the oneliner:
``app.plugins.plugins.dataview.api.pages(\`"${tp.config.template_file.path}"\`)[0].my_template_frontmatter_var``

Wanted to make sure if anyone else was looking to do this they might find a solution.

**Comment by AB1908** [comment] 2023-08-28 14:02
If your template frontmatter is static, you should be able to use `getFileCache()` to retrieve it. See the Obsidian API for details. However, you may want to reconsider how you've written your script and perhaps define the frontmatter as variables instead to use in your script instead of having to go through Obsidian's APIs to fetch what is already defined in the file.
