### ISSUE TITLE
Date not rendered as link

### ISSUE THREAD

**Issue by thomashirtz** [SilentVoid13/Templater#1378] opened 2024-05-19 17:15 UTC
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 2.3.1
-   Obsidian version: 1.5.12

**Describe the bug**
When I try to create this template

```
---
date: [[<% tp.date.now("YYYY-MM-DD") %>]]
created: <% tp.file.creation_date("YYYY-MM-DD HH:mm:ss") %>
tags: 
---
```

The date is not viewed as a link and can't be clicked on it, it just appeared orange. It works if I put a link inside the properties or if I put the [[<% tp.date.now("YYYY-MM-DD") %>]] inside the page. The two at the same time doesn't work

**Expected behavior**
Page link in the property

```
---
project: 
date: [[<% tp.date.now("YYYY-MM-DD") %>]]
created: <% tp.file.creation_date("YYYY-MM-DD HH:mm:ss") %>
tags: 
related:
  - "[[blabla]]"
---
# [[<% tp.file.title %>]] 

[[<% tp.date.now("YYYY-MM-DD") %>]]
```
![image](https://github.com/SilentVoid13/Templater/assets/37740986/32cc60bc-3e2e-42e7-b6a6-94cc1f3718dc)

**Comment by Zachatoo** [comment] 2024-05-19 17:34
Links in properties must be wrapped in double quotes, otherwise they will be parsed as a list, since `[]` denotes a list in YAML. This is a documented behavior [here](https://help.obsidian.md/Editing+and+formatting/Properties#Property+format).

Closing since this is not a bug and not related to Templater. Any links in properties must be wrapped in double quotes, not just Templater links.

**Closed** 2024-05-19 17:34 UTC
Labels: bug
