### ISSUE TITLE
The tp.frontmatter object is empty

### ISSUE THREAD

**Issue by qub3r** [SilentVoid13/Templater#513] opened 2022-01-15 19:59 UTC
**Plugin informations (please complete the following information):**

- OS: macOS
  - ![image](https://user-images.githubusercontent.com/5085620/149634926-9cd8aa10-f265-4af0-a43c-e8d77ea8900e.png)
-   Templater version: 1.9.11
-   Obsidian version: 0.13.19
-   Templater settings: 
![image](https://user-images.githubusercontent.com/5085620/149635125-3128e4a7-de7f-449f-8321-b67f70d9cff0.png)
![image](https://user-images.githubusercontent.com/5085620/149635144-86684d28-1bd3-4ad8-9a1d-f477b954dcd9.png)
![image](https://user-images.githubusercontent.com/5085620/149635234-2a033409-60e8-4ab3-8868-87906125e7d3.png)
![image](https://user-images.githubusercontent.com/5085620/149635243-e4c2663e-0759-4d81-a685-b463ec391f82.png)
![image](https://user-images.githubusercontent.com/5085620/149635252-fc550992-1613-4785-9a76-3896a61d477a.png)

**Describe the bug**
The `tp.frontmatter` object is empty when creating a new file from a template, even when a frontmatter is defined.

I have the following template define at `tools/templates/main/test_template`

```
---
alias: 'foobar'
foo: 'bar'
---

<%* 

    console.log(tp.frontmatter)
    
%>
<% tp.frontmatter.alias %>
<% tp.frontmatter.foo %>

```

The following actions produce the template below
1. Create a new file in the directory `test_folder`.
2. Execute the command "Templater: Create new note from template" from the command palette and select `test_template`.

```
---
alias: 'foobar'
foo: 'bar'
---


undefined
undefined

```

However, when I have the `test_template` template file open and execute the command "Templater: Replace templates in the active file" from the command palette, I get the template output I was expecting.

```
---
alias: 'foobar'
foo: 'bar'
---


foobar
bar

```

**Expected behavior**
I was expecting the frontmatter object to contain the contents of the frontmatter, no matter how the template is executed.

**Screenshots**
The console log output.
![image](https://user-images.githubusercontent.com/5085620/149635949-dd4eb227-b091-4403-9e64-f55618935842.png)

**Additional context**
I have Oblivion's core "Templates" plugin disabled. The `tp.frontmatter` object works as expected in periodic notes.

**Comment by shabegom** [comment] 2022-01-15 20:46
Duplicate of #449

**Closed** 2022-01-15 20:47 UTC
Labels: bug
