### ISSUE TITLE
User templates not working?

### ISSUE THREAD

**Issue by mvanders** [SilentVoid13/Templater#8] opened 2020-11-13 13:18 UTC
I defined:
User Template: `{{my_today}}` with value: `date +"%Y%m%d"`
I created a Template in my ZZ_Templates folder (configured in Templater):
`# {{my_today}} {{templater_file}}`

When trying to use the template, I get: Error with the template n1: check console for more informations.
Output in an empty file called "Test":
`# {{my_today}} Test`

Why?

**Comment by SilentVoid13** [comment] 2020-11-17 15:40
Closing, duplicate of #7

**Closed by SilentVoid13** 2020-11-17 15:40 UTC
