### ISSUE TITLE
Templater complains of "Templater" Folder not present 

### ISSUE THREAD

**Issue by rajeget** [SilentVoid13/Templater#102] opened 2021-04-13 19:26 UTC
On my Obsidian v0.11.13, I am unable to make a hidden folder to hold all templates . For example if I say hold my templates in .obsidian/templater or even .templater . When clicking the templater it complains that folder does not exists .

**Comment by SilentVoid13** [comment] 2021-04-13 19:40
Hey @rajeget, Obsidian does not track hidden folders / files. Therefore, the API doesn't allow to read inside hidden folders, so Templater can't access your templates to read them.
Closing this, since this is not a bug but an obsidian limitation.

**Closed by SilentVoid13** 2021-04-13 19:40 UTC
Labels: bug
