### ISSUE TITLE
Mass creating of notes causes tp.file.rename to rename the wrong file

### ISSUE THREAD

**Issue by dredhorse** [SilentVoid13/Templater#845] opened 2022-09-28 19:18 UTC
Just "hacking" the raindrop.io plugin and try to rename the name of the note via templater code.

That works, but not as it should.

As the plugin is importing around 10 new notes very quickly templater starts running and does as one task the renaming of the note.

The problem is that after some notes (approx 3) it keeps on renaming the same note with the name from the other notes.

It looks like templater is loosing the context in which it should work.

The "template" I use in the raindrop.io plugin:

```js
{% if is_new_article %}
<%*
let newTitle =  "{{title}}"
newTitle = "SM - " + tp.user.j_sanitizeFilename(newTitle)
-%>
> [!METADATA]-
> - Created:: [[<% tp.date.now('YYYY-MM-DD') %>]]
> - Related::
> - up:: 
> - Content:: #content/resource/raindrop
> - Status:: #status/seed
> - Type:: #type/resource/raindrop
{% if tags|length %}> - Document Tags:: #Raindrop/{{ tags | join(", #Raindrop/") }}{% endif %}
{% if excerpt %}> - Summary:: {{excerpt}}{% endif %}
{% if link %}> - Source URL:: {{link}}{% endif %}
---
# [[<% newTitle %>]]

<% await tp.file.rename(newTitle) %>
<% await tp.file.include("[[x_displaySummary]]")%>

{% if link %}{{link}}{% endif %}

{% if cover %}![Cover]({{cover}}){% endif %}

## Highlights
{% endif -%}{% for highlight in highlights %}
{% if highlight.color == "red" -%}
    {%- set callout = "danger" -%}
{%- elif highlight.color == "blue" -%}
    {%- set callout = "info" -%}
{%- elif highlight.color == "green" -%}
    {%- set callout = "check" -%}
{%- else -%}
    {%- set callout = "quote" -%}
{%- endif -%}
> [!{{callout}}]+ Updated on {{highlight.lastUpdate}}
>
> {{highlight.text.split("\n") | join("\n>")}}
{% if highlight.note -%}> > {{highlight.note}}{%- endif %}

{%- endfor -%}
```

**Comment by shabegom** [comment] 2022-09-28 23:11
Interesting use case and problem. Templater should probably process files in sequence so the config object doesn't get overwritten. 

Can you post your sanitization user script?

If the problem is in processing it's not going to be an easy fix unfortunately.

**Comment by dredhorse** [comment] 2022-09-29 09:03
it is probably a little bit overkill https://gist.github.com/barbietunnie/7bc6d48a424446c44ff4
the only changes I made was to remove the truncate part as that doesn't work.

hmm.. just noticed that I don't await the tp.user stuff..

I think the same could happen with any other plugin adding a lot of files and using a template with templater code which then renames the file. I don't know if that would happen with any other templater "command",  <% tp.file.cursor(1) %>  could perhaps also run into a similar problem as it will be triggered for every new file even if the file isn't "used", don't know if Obsidian remembers the cursor position per note.

I think the only way to really fix this would be to spawn a process for every newly created file and hook that process to the file. Perhaps it would be worth to mention that if you are do batch processing of files templater might not work as intended.

**Comment by dredhorse** [comment] 2022-09-29 09:08
just tried it again with the await statement.. this time it even did throw an error:

`plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 ENOENT: no such file or directory, rename '/Best Train Lines for Living in Tokyo The Yamanote Line.md' -> 'SM - 5 Ways to Enjoy Autumn in Japan.md'`
![2022-09-29 11-07-15 - Privat - Obsidian v0 15 6 ](https://user-images.githubusercontent.com/1054143/192990600-57f45914-bd97-4118-aa5e-9619d85a34eb.png)

![2022-09-29 11-08-12 - Privat - Obsidian v0 15 6 ](https://user-images.githubusercontent.com/1054143/192990804-23fb420a-06ed-41c5-bae6-f2900612a2e0.png)

so the missing await wasn't the issue

**Comment by shabegom** [comment] 2022-09-29 12:19
Yeah there doesn't seem to be any async code in the user script.

Here's a random idea. Don't store the title in a `newTitle` variable. Do the rename directly. Turn this:

```js
<%*
let newTitle =  "{{title}}"
newTitle = "SM - " + tp.user.j_sanitizeFilename(newTitle)
-%>
```

Into

```
<%*
await tp.file.rename( "SM - " + tp.user.j_sanitizeFilename("{{title}}"))
-%>

And then do the same thing when setting your h1.

My reasoning is that maybe this is because the `newTitle` variable is being reused across files. Could be totally wrong. Just hoping it isn't a queuing problem...

**Comment by dredhorse** [comment] 2022-09-29 12:54
I changed it (not using the variable) but I would say it is a queuing problem
```
plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 ENOENT: no such file or directory, rename '/Best Train Lines for Living in Tokyo The Yamanote Line.md' -> '/SM - 5 Nature-Themed Activities to Try on Japans Amami Oshima Island.md
```
You can see that the rename is wrong.

![2022-09-29 14-47-53 - Privat - Obsidian v0 15 6 ](https://user-images.githubusercontent.com/1054143/193035473-2a576fd0-f6c3-4526-9941-2d6e131d2f48.png)

**Comment by dredhorse** [comment] 2022-09-29 12:59
btw: I mainly wanted you know that the issue exist with batch / mass creation of notes and templater.

The raindrop plugin doesn't really like the rename of the filenames either so I will need to wait till that is implemented natively.

**Comment by AB1908** [comment] 2022-10-01 21:04
I couldn't repro this.

## Repro info:

- Obs version: 16.3
- Templater version: 1.14.3
- Steps: 
  - Turned on "trigger on new file creation"
  - Created a script that created new files. New files had a templater command to `await tp.file.rename()` with a dynamically generated name.
  - Ran script
  - All files were renamed successfully after repeating these steps twice
- Script:
     ```js
    <%*
    let i = 0;
    for (i=0; i< 10; i++) {
        let s= "repro"+i;
	    await tp.file.create_new(`<%await tp.file.rename("${s}")%>`);
    }
    %>
    ```

**Comment by shabegom** [comment] 2022-10-02 00:02
Thanks @AB1908!

That limits the issue to interaction with the raindrop plugin specifically. Not sure there is anything we can do if that's the case.

**Comment by dredhorse** [comment] 2022-10-02 15:36
you wait the file creation process... I guess you could test that better with creating 10 files with templater commands in there and then copy those files into your vault. Will try that hopefully tomorrow.

**Comment by shabegom** [comment] 2022-10-29 15:40
Closing as I don't think we can address this edge case within templater.

**Closed by shabegom** 2022-10-29 15:40 UTC
Labels: bug
