### ISSUE TITLE
similar to {{note_title}} and {{note_content}} can we have {{note_path}}

### ISSUE THREAD

**Issue by polytrophic** [SilentVoid13/Templater#58] opened 2021-02-10 22:51 UTC
hello,

{{note_title}} is helpful for passing the current daily note to an external program (pwsh) for processing.

however, when not dealing with daily notes it can be tricky if your vault contains files with the same name, but in different directories.

i haven't had success on Windows 10 while passing {{note_content}} to pwsh when the note contains newlines.

is there some way we can pass the path of the note to the external program when using a user configured template?

this example works with notes that do not contain newlines, but not ones that do
![image](https://user-images.githubusercontent.com/1230253/107583200-94dbdc00-6bc8-11eb-9034-7f960a75f437.png)

**Comment by luckman212** [comment] 2021-03-24 12:02
I think this is a duplicate of https://github.com/SilentVoid13/Templater/issues/46 ?

**Comment by SilentVoid13** [comment] 2021-04-06 06:12
Hey @polytrophic, this has been implemented as of Templater 1.0.0. 
If you update, you will now be able to use `<% tp.file.path() %>` to get the full path of a note.
Closing this.

**Closed by SilentVoid13** 2021-04-06 06:12 UTC
Labels: enhancement
