### ISSUE TITLE
User-defined functions break if tools installed with Homebrew are used

### ISSUE THREAD

**Issue by christyray** [SilentVoid13/Templater#512] opened 2022-01-14 19:52 UTC
**Plugin informations (please complete the following information):**

-   OS: macOS Monterey
-   Templater version: 1.9.11
-   Obsidian version: 0.13.19
-   Templater settings: Template folder location: "templates/", Timeout: "5", Trigger on New File Creation, User System Command Functions enabled

**Describe the bug**
When I create a user function that relies on a tool installed with Homebrew, I get the error `command not found`. If I specify the path to the alias created by Homebrew (e.g., `/user/local/bin/toolname`), I get the error `env: node: No such file or directory`. 

It appears to be specific to tools installed with Homebrew. I have other user functions that only use standard shell tools, and they work fine, but I've tried multiple Homebrew tools, and they all give the same error. 

Two of the functions that I tried were:
* `curl -s https://api.weather.gov/gridpoints/LWX/109,90/forecast | /usr/local/bin/fx '.properties.periods[0].detailedForecast'` - `fx` is a command-line tool I installed with Homebrew
* `/usr/local/bin/tldr curl`- `tldr` is another command-line tool I installed with Homebrew (the expected output of the command is a plain-text summary of the `curl` documentation)

These both gave the `env: node: No such file or directory` error.

**Expected behavior**
I expected the shell command to work inside Templater like it does when I execute it at the command line. 

**Additional context**
It looks like I'm having the same issue that was described in [this forum post](https://forum.obsidian.md/t/help-with-templater-error-when-running-custom-function/24132), if that helps give more information!

**Comment by shabegom** [comment] 2022-01-14 21:46
@christyray Please fill out the bug report template.

**Comment by christyray** [comment] 2022-01-14 22:11
@shabegom - I'm sorry for the confusion, but I thought I did? I updated it to add the rest of my settings and two of the functions I tried - is there anything else that would be helpful for me to add?

**Comment by shabegom** [comment] 2022-01-15 17:28
@christyray hrm this is all I see right now...

![image](https://user-images.githubusercontent.com/5445691/149631522-3529c745-75d3-4d62-83be-1f9c7b3999a9.jpeg)

I'm not sure what's happening, maybe repost as a comment?

**Comment by christyray** [comment] 2022-01-15 17:48
@shabegom - that is odd! I pasted the text below, hopefully it works this time!

**Plugin information:**

-   OS: macOS Monterey
-   Templater version: 1.9.11
-   Obsidian version: 0.13.19
-   Templater settings: Template folder location: "templates/", Timeout: "5", Trigger on New File Creation, User System Command Functions enabled

**Describe the bug**
When I create a user function that relies on a tool installed with Homebrew, I get the error `command not found`. If I specify the path to the alias created by Homebrew (e.g., `/user/local/bin/toolname`), I get the error `env: node: No such file or directory`. 

It appears to be specific to tools installed with Homebrew. I have other user functions that only use standard shell tools, and they work fine, but I've tried multiple Homebrew tools, and they all give the same error. 

Two of the functions that I tried were:
* `curl -s https://api.weather.gov/gridpoints/LWX/109,90/forecast | /usr/local/bin/fx '.properties.periods[0].detailedForecast'` - `fx` is a command-line tool I installed with Homebrew
* `/usr/local/bin/tldr curl`- `tldr` is another command-line tool I installed with Homebrew (the expected output of the command is a plain-text summary of the `curl` documentation)

These both gave the `env: node: No such file or directory` error.

**Expected behavior**
I expected the shell command to work inside Templater like it does when I execute it at the command line. 

**Additional context**
It looks like I'm having the same issue that was described in [this forum post](https://forum.obsidian.md/t/help-with-templater-error-when-running-custom-function/24132), if that helps give more information!

**Comment by christyray** [comment] 2022-01-20 22:13
Update: based on [this issue with the Obsidian Git plugin](https://github.com/denolehov/obsidian-git/issues/14), it looks like the problem is that the `obsidian` process doesn't include `/usr/local/bin` in its `PATH`, and that's where Homebrew places symlinks to any packages it installs. 

Based on the suggestions in that issue, I rewrote my user-defined function as a bash script with `PATH=$PATH:/usr/local/bin` at the top, and then created a function in Templater to run that script. This worked to fix my issue without needing to reinstall the packages separate from Homebrew. 

I'm not sure if this is fixable within the plugin since it seems to be a problem with Obsidian itself (although I could be totally off-base), but I'm not bothered by just writing separate scripts instead of directly pasting the code in Templater.

**Comment by shabegom** [comment] 2022-01-21 01:38
Yeah I noticed that the $PATH being used when triggering templater is different from the $PATH defined in a .bashrc.

Templater is using Node's `child_process` to run the shell script. If the issue is with templater that would be where.

**Comment by shabegom** [comment] 2022-01-24 13:07
Great sleuthing. This problem comes up more than I would expect so we should either add the feature to Templater, fix it in obsidian, or point towards another solution. I'll close this, but if you choose to push your plugin to github let me know so I can link it as a workaround.

**Closed by shabegom** 2022-01-24 13:07 UTC
Labels: bug
