### ISSUE TITLE
live preview doesn't work while using html label

### ISSUE THREAD

**Issue by QuanPie** [SilentVoid13/Templater#1127] opened 2023-06-15 05:54 UTC
-   OS: MacOS 13.1
-   Templater version: 1.16.0
-   Obsidian version: v1.3.5
-   Templater settings: default

**Describe the bug**
- live preview doesn't work while using html label.
- when I turn off the plugin, live preview works fine.

**Screenshots**
- live preview didn't work at the content behind html labels
<img width="753" alt="image" src="https://github.com/SilentVoid13/Templater/assets/47452844/e011af51-bc06-4ff1-bf97-a01d458db2e6">

**Comment by Zachatoo** [comment] 2023-06-18 12:47
Can you copy/paste the source markdown you're using in that example? I'm not seeing this issue on my end, though I'm using English characters.

Here's the markdown source I tested with:
```md
# 1. test

- One line
- Line with <font style="color: #fff">fonts</font>
- Another line
- Another line with <font style="color: #ffffff">fonts</font> , and more content
```

**Comment by cream314159** [comment] 2023-06-19 05:46
> Can you copy/paste the source markdown you're using in that example? I'm not seeing this issue on my end, though I'm using English characters.
> 
> Here's the markdown source I tested with:
> 
> ```lisp
> # 1. test
> 
> - One line
> - Line with <font style="color: #fff">fonts</font>
> - Another line
> - Another line with <font style="color: #ffffff">fonts</font> , and more content
> ```

Sure, here's the markdown source code I use.
```
---
aliases: 常模, norm
tags: tags/Statistics
source: 
created: 2023-06-06 19:20
modified: <%+ tp.file.last_modified_date() %>
summary: 
---
type:: #types/📚_study
evergreenNote:: #🔅/🌱
mastery:: #🎓

---

# 常模 Norm
## 1. 常模
- 常模是「平凡的」、「既然的」
- 常模的用意是標準化測驗中的平均表現
- 常模用來解釋分 <font style="color: #F7CE46">數意義團體中的相對位置 </font>
- 常模是可變動的
- 藉由 <font style="color: #F7CE46; "> 常模 </font> ，可將**原始分數** <font style="color: #F7CE46; ">轉化為衍生分數</font>
	- 衍生分數 derived_score：
		- 為不同的測驗提供相同的度量
		- 評估在團體中的相對地位
- 常模案例：平均值、標準差、百分位數、標準分數

## 2. 常模種類
- 發展性常模 development_norms
	- 年齡常模
	- 年級常模
- 團體內常模 within-group_norm
	- 百分位數常模
	- 標準分數常模
- [[衍生分數]]
	- ![[norm.jpeg]]
## 3. 校準常模
- 增進兩種以上測驗的可比性
- 簡便途徑發展新測驗
```

And I tried the markdown source code you tested with, same issue on my computer.
<img width="1440" alt="image" src="https://github.com/SilentVoid13/Templater/assets/47452844/5eaaeaf1-38bf-4e5e-a4ae-5cf97a7238a3">

**Comment by cream314159** [comment] 2023-06-19 06:12
I also tested it in a new vault, and it worked fine. It seems that the problem may be specific to my environment.

Here's what I tried, and didn't work:

- In the environment where the issue occurs, I disabled other plugins and only kept Templater enabled, but the issue still persists.
- Reinstall the plugin

**Comment by Zachatoo** [comment] 2023-06-20 14:02
Did you restart after disabling all other plugins? Some plugins don't properly unload until Obsidian is restarted. Could still be another plugin.

**Comment by cream314159** [comment] 2023-06-21 16:49
Thank you for the reply. I have already fixed the issue by rebasing the `.obsidian` folder, so I am not sure if it was caused by another plugin or not.

**Comment by Zachatoo** [comment] 2023-10-04 02:40
If you still aren't experiencing the issue, mind if we close this issue?

**Comment by QuanPie** [comment] 2023-10-07 11:26
> If you still aren't experiencing the issue, mind if we close this issue?

Sure! thank you for your help.

**Closed** 2023-10-07 19:52 UTC
Labels: bug, awaiting response
