### ISSUE TITLE
Target file gets overwritten by processFrontMatter()

### ISSUE THREAD

**Issue by ljavuras** [SilentVoid13/Templater#1393] opened 2024-06-06 21:41 UTC
**Plugin information:**

-   OS: Windows 10
-   Templater version: 2.3.3
-   Obsidian version: 1.5.12
-   Templater settings: 

**Describe the bug**
Consider this example template:
```javascript
<%*
// Modify frontmatter after template execution is done
tp.hooks.on_all_templates_executed(async () => {
    app.fileManager.processFrontMatter(
        tp.config.target_file,
        (frontmatter) => { frontmatter['demo_property'] = "demo_value" }
    );
});
-%>
Template content (which should remain after this example template is inserted)
``` 

Steps to reproduce:
1. Create a new empty note
2. Run templater command and insert the above template

**Expected behavior**
Expected outcome should be:
```
---
demo_property: demo_value
---
Template content (which should remain after this example template is inserted)
``` 
However the actual result is:
```
---
demo_property: demo_value
---
``` 

This bug occurs only while inserting into an empty note; if the note isn't empty, it behaves as expected, with the message `"Untitled" has been modified externally, merging changes automatically.` If you create new note from this template, it behaves as expected.

**Comment by McGlear** [comment] 2024-06-07 12:16
Duplicate of  #1309

**Closed** 2024-06-07 14:37 UTC
Labels: bug
