### ISSUE TITLE
Way to share variables between template blocks

### ISSUE THREAD

**Issue by jonasmerlin** [SilentVoid13/Templater#221] opened 2021-05-15 21:31 UTC
So this is either a question or, depending on the answer, a feature request. 😄

I came up with the following template to create Anki card notes for the Obsidian_to_Anki plug-in:

``` javascript
<%*
    const decks = await app.vault.getAbstractFileByPath("Flashcards")?.children?.filter(f => f.children).map(d => d.name)
    const deck = await  tp.system.suggester(decks, decks)
    const title = await tp.system.prompt("Title")
    await tp.file.move(`/Flashcards/${deck}$/${title}`) 
    await tp.file.rename(`${title}`)
%>

TARGET DECK: // wanna use `deck` from above here

START
Basic
Front: // wanna use `title` from above here
Back: <% tp.file.cursor(1) %>
END
```

I get the deck it's supposed to go in as well as the title upfront. I use both to move the note to the correct location. And then I want to use both later on in the note again. I marked these spots with comments above. Is there a way to do that currently, without having to get them again?

**Comment by SilentVoid13** [comment] 2021-05-22 23:09
Closing as this is a duplicate of #232

**Closed by SilentVoid13** 2021-05-22 23:09 UTC
Labels: question
