### ISSUE TITLE
tp.file.cursor() not working on iPad

### ISSUE THREAD

**Issue by SamAdams51** [SilentVoid13/Templater#547] opened 2022-02-04 20:27 UTC
**Plugin informations (please complete the following information):**

-   OS: iPadOS 15.3 
-   Templater version: 1.10.0
-   Obsidian version: 1.0.5 (mobile)
-   Templater settings: -

**Describe the bug**
Hi, first of all, many thanks for this fantastic plug-in. But here is a little bug:

The cursor movement in the attached template works super when I use it on my Mac with the newest macOS. However, when I am working on my iPad and insert the template in a new note, the cursor goes straight to the bottom of the note.
[Rezeptvorlage.md](https://github.com/SilentVoid13/Templater/files/8006003/Rezeptvorlage.md)

**Expected behavior**
Same cursor movement as on mac.

**Comment by shabegom** [comment] 2022-09-01 22:36
duplicate of #408

**Closed by shabegom** 2022-09-01 22:36 UTC
Labels: bug
