### ISSUE TITLE
[Bug]: IntelliSense about `file.move` function is not correct

### ISSUE THREAD

**Issue by hustrjh** [SilentVoid13/Templater#986] opened 2023-01-08 02:51 UTC
**Plugin information (please complete the following information):**

-   OS: Windows 10
-   Templater version: 1.16.0
-   Obsidian version: 1.1.9

**Describe the bug**
IntelliSense about **`file.move`** function is not correct. There is no **`file.functions.move()`** function at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/69783980/211178185-49760cab-10e7-4a16-af50-40b9ab04832a.png)

**Comment by Zachatoo** [comment] 2023-10-04 03:10
Marking as duplicate of #1136 since it has more context

**Closed by Zachatoo** 2023-10-04 03:10 UTC
Labels: bug, duplicate
