### ISSUE TITLE
Emoji's are not supportet

### ISSUE THREAD

**Issue by RrobertRr** [SilentVoid13/Templater#9] opened 2020-11-13 16:40 UTC
When I try to print an emoji, it fails.
I'm using Windows.

**Comment by SilentVoid13** [comment] 2020-11-17 16:05
Hello @RrobertRr, thanks for reporting this issue !
Could you specify in what context you want to be using emojis ? What is the associated command for your template ?

**Comment by unstppbl** [comment] 2020-11-24 06:36
Hello @SilentVoid13 , the template is {{weather}}, and for it to work on Windows 10 I had to change the command a bit:
```powershell
powershell ((Invoke-WebRequest -UseBasicParsing -Uri wttr.in/Astana?format=3).Content)
```
But it shouldn't affect the emojis, so I assume the problem is in Templater plugin.

The output of the template:
![image](https://user-images.githubusercontent.com/13606833/100057452-adeab180-2e51-11eb-9712-1d0045829174.png)

**Comment by unstppbl** [comment] 2020-11-24 06:37
I tried to use regular expressions to replace emojis part, but degree symbol is also not supported

**Comment by SilentVoid13** [comment] 2020-11-26 17:47
Hi @unstppbl, it looks like powershell does not like emojis, tried running the command from a powershell shell and got a bunch of junk like you did.
Tell me if you find a solution for this, but I think that it's just not possible to use emojis in powershell.

**Comment by vikingsc2007** [comment] 2021-01-07 11:53
Same problem on Windows10 1901 (language zh-cn)

You need PowerShell UTF-8 Support

Open your powerShell ，Execute command `New-Item $PROFILE -ItemType File -Force`
Then open result url  `.ps1` file in notepad ,append `[System.Console]::OutputEncoding=[System.Text.Encoding]::GetEncoding(65001)`
Back to your powerShell, Execute command `Set-ExecutionPolicy Unrestricted`

**Comment by luckman212** [comment] 2021-04-21 13:37
Found a solution: https://github.com/SilentVoid13/Templater/issues/15#issuecomment-824067020

**Comment by SilentVoid13** [comment] 2021-04-22 15:40
As @luckman212 said, unicode chars problems are not coming from Templater, but from cmd.exe and powershell.
I added some documentation on solutions to fix this problem: https://silentvoid13.github.io/Templater/docs/faq#unicode-characters-emojis--are-not-working-on-windows-
Closing this.

**Closed by SilentVoid13** 2021-04-22 15:40 UTC
Labels: bug
