### ISSUE TITLE
user function seems not to work on mobile

### ISSUE THREAD

**Issue by ebullient** [SilentVoid13/Templater#223] opened 2021-05-16 13:33 UTC
**Plugin informations (please complete the following information):**
 - OS: iOS 14.4.2
 - Templater version: 1.6.0
 - Obsidian version: 0.0.19
 - Templater settings: {"command_timeout":5,"template_folder":"[assets]/templates","templates_pairs":[["",""]],"trigger_on_file_creation":true,"enable_system_commands":false,"shell_path":"","script_folder":"[assets]/scripts"}

**Describe the bug**
This will take some explaining. Let's start with what works everywhere. I have a daily template that looks like this: 

```
<%* var titledate = tp.file.title;
const today = moment(titledate).isoWeekday();
    var nextworkday = moment(titledate).add(1, 'd');
    var thisweek = moment(titledate).day(1);
    var tomorrow = 'tomorrow';
    if (today === 1 ) {
        thisweek = moment(titledate);
    } else if (today > 4) {
        nextworkday = moment(titledate).startOf('isoWeek').add(1, 'week').day("monday");
        tomorrow = 'Monday';
    }
    tR +=  '# My Day\n'
        + moment(titledate).format("dddd, MMMM DD, YYYY") 
        + ' .... ['+tomorrow+'](' + nextworkday.format("YYYY-MM-DD")+')  \n'
        + 'Week of ['+thisweek.format("MMMM DD")+'](../weekly/Week-'+thisweek.format("YYYY-MM-DD")+')  \n';
%>
```

If I try to break this into a user function, it works on desktop, but not on mobile. Specifically, I tried replacing the template content with this:

```
<%* var titledate = tp.file.title;
const today = moment(titledate).isoWeekday();
tR += tp.user.daily(today, titledate); 
%>
```
(I use those variables elsewhere, which also seems not to work on mobile with the user function in the mix... works fine on desktop).

My user function (in the scripts folder configured above) is in a file called `daily.js`, and it looks like this:

```js
function daily(today, titledate) {
    var nextworkday = moment(titledate).add(1, 'd');
    var thisweek = moment(titledate).day(1);
    var tomorrow = 'tomorrow';
    if (today === 1 ) {
        thisweek = moment(titledate);
    } else if (today > 4) {
        nextworkday = moment(titledate).startOf('isoWeek').add(1, 'week').day("monday");
        tomorrow = 'Monday';
    }
    return '# My Day\n'
        + moment(titledate).format("dddd, MMMM DD, YYYY") 
        + ' .... ['+tomorrow+'](' + nextworkday.format("YYYY-MM-DD")+')  \n'
        + 'Week of ['+thisweek.format("MMMM DD")+'](../weekly/Week-'+thisweek.format("YYYY-MM-DD")+')  \n';
}
module.exports = daily;
```

**Expected behavior**
would love to be able to simplify my templates and use functions, but it needs to work on mobile, too.

enhancement request: would be lovely to have a debug flag to turn on for mobile that would write a log.. hacking the plugin to spit out log files on mobile isn't my favorite (i worry about making the problem worse). a debug log that captured the information you need could make filing useful bug reports easier in general?)

**Comment by SilentVoid13** [comment] 2021-05-22 23:21
Hey @ebullient, you are correct user script functions are not working on mobile atm, but that's because I have to use the obsidian API `FileSystemAdapter` feature that isn't available on mobile. 
Whenever the obsidian team adds the mobile equivalent to this, I'll add support for mobile.

**Comment by ankushg** [comment] 2021-05-28 07:16
@SilentVoid13 Is `this.app.vault.adapter.getBasePath()` the only method you need from `FileSystemAdapter`? Just want to make sure I understand what the current limitation is 😄

**Comment by SilentVoid13** [comment] 2021-06-17 15:01
Hey @ankushg, yes that's literally the only thing that I need but that's only available on desktop. I basically need the full path to the js file to `import` it. I couldn't find a solution to this problem, but if you found something I'd be curious to know.

**Comment by ruqqq** [comment] 2021-06-20 11:19
I did these:
1. Hardcoding the base path (I'm on android so it starts with /storage/emulated/0/Documents/Obsidian)
2. Disable this code path https://github.com/SilentVoid13/Templater/blob/589094a9ae4316eb392c924292ba1ab41ac0b338/src/UserTemplates/UserTemplateParser.ts#L54 - window.require is undefined on mobile

Now I am getting the error: `Failed to load user script ${file_path}. No exports detected.`

Is import directive even supported on mobile/android?

**Comment by lishid** [comment] 2021-07-08 23:11
> Hey @ankushg, yes that's literally the only thing that I need but that's only available on desktop. I basically need the full path to the js file to `import` it. I couldn't find a solution to this problem, but if you found something I'd be curious to know.

`getBasePath` does not exist on mobile because there is no basepath. On Mobile, we get wildly different paths depending on the platform - on Android we'll sometimes get `content://` paths, sometimes get `file:///` paths, and sometimes get `/storage/`paths. On iOS we get some weird `http://localhost:port/` paths, or sometimes a `file:///` path. The platform does some additional encoding of URIs depending on whether it's URI based or path based.

You'll want to use the getResourcePath if you want to load it as a URL in the browser; this will get you an URI that is handled by the platform that can load in the WebView. Otherwise, you should rely on `vault.read(file)` to get the contents, and run the contents of the file.

**Comment by chaseadamsio** [comment] 2021-07-14 16:27
@SilentVoid13 I opened a PR to update the docs (#282) as a temporary measure to let folks know user functions aren't currently available on mobile.

**Comment by shabegom** [comment] 2021-08-20 21:10
@SilentVoid13 what if we tried something like:

```
const user_function_raw = this.app.vault.read(file)

const user_function = user_function_raw.replace(/module.exports(.+)\n/, "")

const fn = window["user_function"];
if(typeof fn === 'function') {
    this.user_script_functions.set(`${file.basename}`, fn);
```
Or if we don't have access to the `window` object use the `Function` constructor:

`const fn = Function(user_function)`

I'm not near a computer to try this out, but will test next week and open a PR if it works...

**Comment by shabegom** [comment] 2021-08-24 00:29
Update: I tested it, and believe my approach above will work! Will submit the PR tomorrow for review.

**Comment by shabegom** [comment] 2021-08-24 16:28
PR #340 submitted

**Comment by beingskyler** [comment] 2021-10-01 12:41
Did this ever get resolved? Will gladly fund development if needed.

**Comment by ebullient** [comment] 2021-10-01 13:13
As another option: I switched over to using the CustomJS plugin with both Templater and Dataview.

**Comment by Dyldog** [comment] 2021-11-11 03:32
@ebullient Are you showing any prompts from your CustomJS scripts? If so, how?

**Comment by lishid** [comment] 2021-11-11 03:58
@SilentVoid13 I took a look at how you're loading the script - I see that you're using the absolute path because you're using NodeJS's import function, which is why it'll never work on mobile.

The way I recommend you to change this for mobile support, is to load the file into a string using `vault/adapter.read` (relative to vault root), and then call `eval`.

The way we load plugins, for example, is to do this:

```ts
let js = await adapter.read(file_path);

let require = window.require;
let exports: any = {};
let module = {exports};

window.eval('(function anonymous(require,module,exports){' + js + '\n})');
fn(require, module, exports);

let result = exports['default'] || module.exports;
```

**Comment by ebullient** [comment] 2021-11-11 13:21
> @ebullient Are you showing any prompts from your CustomJS scripts? If so, how?

I use Templater if/when I need prompts, and CustomJS usually for computation/functions or custom filters, etc.

**Comment by shabegom** [comment] 2021-11-11 18:16
> The way I recommend you to change this for mobile support, is to load the file into a string using vault/adapter.read (relative to vault root), and then call eval.

This is basically the approach I took in PR #340. I just don't think SV has had time to review/merge the change.

CustomJS is a decent workaround for now, it uses a similar approach (vault.read) so works on mobile.

**Comment by shabegom** [comment] 2022-01-13 16:04
Update: going to revisit my PR and merge if it still is working properly. Stay tuned!

**Comment by ebullient** [comment] 2022-01-13 16:42
worth considering if CustomJS should just be the way. Scope creep is a thing. ;) (And CustomJS works with dataview, too.. )

**Comment by ebullient** [comment] 2022-01-13 19:30
> @ebullient Are you showing any prompts from your CustomJS scripts? If so, how?

Yes.. but I pass tp in, and use tp to do it. Its a very nice mix and match.

**Comment by shabegom** [comment] 2022-01-24 12:59
Friends! SV has released 1.10.0 which fixes support for user scripts on mobile. Closing this issue! 🎉

**Closed** 2022-01-24 12:59 UTC
Labels: bug

**Comment by AB1908** [comment] 2022-01-29 22:53
@ebullient have you had a chance to test this out?

**Comment by ebullient** [comment] 2022-01-30 03:23
No.. I've moved everything over to CustomJS in the meanwhile ...

**Comment by danielo515** [comment] 2023-08-28 16:27
So far, user functions have been working fine for me on mobile. However, I still see lots of references about them not working on mobile. Should the docs (and forum posts whenever possible) be updated?

**Comment by easyas314** [comment] 2024-08-09 19:28
I realize this is closed, however just an fyi - on Templater 2.4.1 my user function works fine on Linux, but fails on Android 14 and on ChromeOS Version 126.0.6478.222 (Official Build) (64-bit).

**Comment by Zachatoo** [comment] 2024-08-21 01:57
@easyas314 I just tested on Templater 2.4.1 Android 14 and my user functions work for me. Can you provide more details in a separate issue or discussion? I need to know the contents of the user function and what the error message was, if there was one. I haven't heard any other reports of it not working in the last 2 weeks so the problem is likely specific to your script or setup.

**Comment by maxencevm** [comment] 2025-01-14 16:43
Hello,

I also had an issue with user scripts on mobile.

A script that worked on the computer returned `tp.user.myScript isn't a function` on mobile.

According to the console, the script named `myScript()` but contained in a `MyScript.js` file was properly loaded.

However, while the script worked both with and without capitalization on the computer, it required capitalization on mobile (`tp.user.MyScript()`).

The issue is now resolved, but I hope this helps others.

_This message is translated. My apologies for any errors._

**Comment by filprpx** [comment] 2025-05-22 23:54
To anyone coming to this thread, I was also unable to use user functions, turns out the obsidian sync was not configured to sync my js files (They were never created on my phone).

Settings > Sync > Selective Sync > Sync all other types

**Comment by aderchox** [comment] 2026-02-26 11:37
**UPDATE 2:** Ah not fixed yet! Even with the new version that doesn't rely on Intl, **it's not working and still showing error on Obsidian Android**.

**UPDATE:** With help from ChatGPT I realized what was wrong and also received a workaround . **Since Obsidian Android uses WebView, which has only limited ICU support (in contrast to the Chromium/Electron desktop version's use of full build), the issue was, Intl wasn't working on Android.** Also the [only] workaround was doing calendar conversions manually.

This templater user script is working on Obsidian Desktop, but not on Obsidian Android:

The user script:
```js
//date_utils.js
module.exports = (calendar_type) => {
  const now = new Date();

  var ct;
  if (calendar_type === "fa") {
    ct = "fa-IR-u-ca-persian";
  } else if (calendar_type === "en") {
    ct = "en-US-u-ca-gregory";
  } else if (calendar_type === "ar") {
    ct = "ar-SA-u-ca-islamic";
  } else {
    ct = "en-US-u-ca-gregory";
  }

  const longDate = new Intl.DateTimeFormat(ct, {
    year: "numeric",
    month: "long",
    day: "2-digit",
  });

  const weekDay = new Intl.DateTimeFormat(ct, {
    weekday: "long",
  });

  return {
    longDate: longDate.format(now),
    weekDay: weekDay.format(now),
  };
};
```

The Templater template:
```md
<%*
var fa_date = tp.user.date_utils('fa');
var ar_date = tp.user.date_utils('ar');
var en_date = tp.user.date_utils('en');
%>


| **<% fa_date.weekDay %>**  |
| -------------------------- |
| **<% fa_date.longDate %>** |
| <% ar_date.longDate %>     |
| <% en_date.longDate %>     |
```

Anyone could help me realize what's wrong?

**Comment by Zachatoo** [comment] 2026-02-26 14:07
@aderchox Please create a new bug report so you aren't sending notifications to everyone in this thread, with your updated script. Also please test with an extremely simplified script (such as just returning the input) to validate that it's an issue with your code and not a bug with Templater.

Locking this thread.
